version: '2'

volumes:
  php-fpm-sock:

services:
  nginx:
    container_name: laravel-nginx
    build: ./nginx/
    image: laravel-nginx
    ports:
      - '80:80'
    volumes:
      - ~/git/menta/issue13-2:/var/www/app:delegated
      - php-fpm-sock:/var/run/
    tty: true
    depends_on:
      - app
  app:
    container_name: laravel-app
    build: ./app/
    image: laravel-app
    volumes:
      - ~/git/menta/issue13-2:/var/www/app:delegated
      - php-fpm-sock:/var/run/
    tty: true
    depends_on:
      - db
      - redis
  db:
    container_name: laravel-db
    build: ./mysql/
    image: laravel-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: app
    volumes:
      - ./mysql/db_data:/var/lib/mysql
  redis:
    container_name: laravel-redis
    image: "redis:latest"
    ports:
      - '6379:6379'
    volumes:
      - ./redis/db_data:/data
