---
new_users:
  menta:
    comment: "Add User menta"
    initial_password: "{{ lookup('env', 'ANSIBLE_MENTA_PASSWORD') | password_hash('sha512') }}"
    groups: menta
    add_sudoers: true
    priv: stg
