---
- name: Ensure Nginx is installed
  apt:
    name: nginx
    state: present

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true

- name: Copy Nginx conf
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ copy_nginx_conf | dict2items }}"
  notify: restart nginx

- name: Copy VirtualHosts conf
  template:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ copy_virtualhosts_conf | dict2items }}"
  notify: restart nginx