---
- name: update apt cache
  apt:
    update_cache: true

- name: Install the latest version of Nginx
  apt:
    name: nginx
    state: latest

- name: ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true

- name: Copy Nginx related files
  copy:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ copy_setting_files | dict2items }}"
  notify: restart nginx

- name: Create directory for documentroot
  file:
    path: "{{ item.value.path }}"
    state: "{{ item.value.state }}"
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
  loop: "{{ add_documentroot_directory | dict2items }}"
  notify: restart nginx

- name: Test Nginx configuration syntax
  command: nginx -t
  register: nginx_test_result
  ignore_errors: true

- name: Fail if Nginx configuration test failed
  fail:
    msg: "Nginx configuration test failed!"
  when: nginx_test_result.rc != 0